---
- name: install haproxy
  become: true
  become_method: sudo
  apt:
    pkg:
      - haproxy
    state: latest
    force_apt_get: true
    update_cache: yes

- name: copy cert generation script to host
  become: true
  become_method: sudo
  template:
    src: generate_certs.j2
    dest: /tmp/generate_certs.sh
    mode: '0755'

- name: run cert generation script
  become: true
  become_method: sudo
  shell: /tmp/generate_certs.sh

- name: create haproxy config file
  become: true
  become_method: sudo
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0775

- name: restart haproxy service
  become: true
  become_method: sudo
  systemd:
    name: haproxy
    enabled: yes
    state: restarted

# ---
# - import_tasks: install_haproxy.yml
# - import_tasks: install_certbot.yml
# - import_tasks: setup_certbot_script.yml
