---
portainer_admin_port: 9000
portainer_network_name: portainer_agent_network
portainer_volume_path: /mnt/portainer_data
portainer_app_name: portainer
portainer_admin_password: password1234
portainer_agent_secret: mysecrettoken
haproxy_stats_user: admin
haproxy_stats_password: password1234
