---
app_domain_name: omydev.com
gluster_volume_path: /glusterfs/bricks
gluster_volume_name: gfs
gluster_mount_path: /mnt/gfs
portainer_admin_port: 9000
portainer_tunnel_port: 8000
portainer_gfs_subdir: portainer
portainer_network_name: portainer_agent_network
portainer_volume_name: portainer_data
portainer_app_name: portainer
portainer_admin_password: password1234
portainer_agent_secret: mysecrettoken
traefik_listen_port: 80
traefik_ssl_listen_port: 443
traefik_admin_port: 8080
traefik_network_name: web
traefik_app_name: traefik
traefik_admin_user: admin
traefik_admin_password: password1234
haproxy_stats_user: admin
haproxy_stats_password: password1234
webserver: haproxy
certbot_email: thienhaole92@gmail.com
domains: 
  - portainer.omydev.com
  - traefik.omydev.com
  - api8.omydev.com
nginx_custom_configurations:
  server_names_hash_bucket_size: 64
nginx_sites:
  portainer:
    letsencrypt: true
    domains:
      - portainer.omydev.com
      - www.portainer.omydev.com
    services:
      - service_name: swarm
        balancing_type: 'ip_hash'
        addresses:
          - 172.31.20.251:80
          - 172.31.20.38:80
          - 172.31.20.89:80
    locations:
      - location: /websocket
        websocket: true
        proxy_pass: 'http://swarm:5000'
      - location: /
        proxy_pass: 'http://swarm'
  traefik:
    letsencrypt: true
    domains:
      - traefik.omydev.com
      - www.traefik.omydev.com
    services:
      - service_name: swarm
        balancing_type: 'ip_hash'
        addresses:
          - 172.31.20.251:80
          - 172.31.20.38:80
          - 172.31.20.89:80
    locations:
      - location: /
        proxy_pass: 'http://swarm'
  api8:
    letsencrypt: true
    domains:
      - api8.omydev.com
      - www.api8.omydev.com
    services:
      - service_name: swarm
        balancing_type: 'ip_hash'
        addresses:
          - 172.31.20.251:80
          - 172.31.20.38:80
          - 172.31.20.89:80
    locations:
      - location: /
        proxy_pass: 'http://swarm'
