---
- name: setup pre-requisites
  hosts: all
  become: yes
  roles:
    - host-defaults
    - docker
    - docker-compose

- name: add managers to the swarm
  hosts: managers
  become: yes
  roles:
    - docker-swarm-add-manager

- name: add workers to the swarm
  hosts: workers
  become: yes
  roles:
    - docker-swarm-add-worker

- name: configures the second drive (sdb) with a XFS file system
  hosts: glusters
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: gluster

- name: deploy portainer and traefik
  hosts: managers
  become: yes
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: traefik
    - import_role:
        name: portainer

- name: deploy haproxy
  hosts: haproxy
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: haproxy