---
- name: setup pre-requisites
  hosts: all
  become: yes
  roles:
    - host-defaults
    - docker
    - docker-compose

- name: add managers to the swarm
  hosts: managers
  become: yes
  roles:
    - docker-swarm-add-manager

- name: add workers to the swarm
  hosts: workers
  become: yes
  roles:
    - docker-swarm-add-worker