---
- name: verify gluster mount path
  become: true
  become_method: sudo
  file:
    path: "{{gluster_mount_path}}"
    state: directory

- name: mount gluster volume {{gluster_volume_name}} to {{gluster_mount_path}}
  become: true
  become_method: sudo
  mount:
    path: "{{gluster_mount_path}}"
    src: "localhost:/{{gluster_volume_name}}"
    fstype: glusterfs
    opts: defaults,_netdev,backupvolfile-server=localhost
    state: mounted
