---
- name: create xfs path {{gluster_volume_path}}/{{inventory_hostname}}
  become: true
  become_method: sudo
  file:
    path: "{{gluster_volume_path}}/{{inventory_hostname}}"
    state: directory
    mode: 0775

- name: create a xfs filesystem on {{device2_hdd_dev}}
  become: true
  become_method: sudo
  filesystem:
    fstype: xfs
    dev: "{{device2_hdd_dev}}"

- name: mount xfs volume {{device2_hdd_dev}} to {{gluster_volume_path}}/{{inventory_hostname}}
  become: true
  become_method: sudo
  mount:
    path: "{{gluster_volume_path}}/{{inventory_hostname}}"
    src: "{{device2_hdd_dev}}"
    fstype: xfs
    state: mounted

# - name: ensure mount paths permissions
#   file: 
#     path: "{{gluster_volume_path}}/{{inventory_hostname}}"
#     state: directory
#     mode: 0775