$nodes = 5

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
    (0..($nodes - 1)).each do |i|
      config.ssh.forward_agent = true
      config.vm.define name="node-#{i}", primary: (i == 0), autostart: (i == 0) do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: "192.168.50.#{20+i}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
    end
  end
end