---
- name: verify stacks directory exists (on first swarm node)
  when: inventory_hostname == groups['controller'][0]
  file:
    path: "/home/{{ansible_user}}/stacks"
    state: directory

- name: verify portainer volume path (on first swarm node)
  when: inventory_hostname == groups['controller'][0]
  become: true
  become_method: sudo
  file:
    path: "{{portainer_volume_path}}"
    state: directory

- name: generate admin password hash
  when: inventory_hostname == groups['controller'][0]
  shell: echo $(htpasswd -nBb admin {{portainer_admin_password}}) | cut -d ":" -f 2 | sed -e s/\\$/\\$\\$/g
  register: portainerpassword

- name: create docker-compose stack file (on first swarm node)
  when: inventory_hostname == groups['controller'][0]
  template:
    src: portainer-agent-stack.j2
    dest: /home/{{ansible_user}}/stacks/portainer-agent-stack.yml
    mode: 0775

- name: install jsondiff python library
  when: inventory_hostname == groups['controller'][0]
  become: true
  become_method: sudo
  pip:
    name: jsondiff

- name: install pyyaml python library
  when: inventory_hostname == groups['controller'][0]
  become: true
  become_method: sudo
  pip:
    name: pyyaml

- name: deploy stack from a compose file (on first swarm node)
  when: inventory_hostname == groups['controller'][0]
  docker_stack:
    state: present
    name: portainer
    compose:
      - /home/{{ansible_user}}/stacks/portainer-agent-stack.yml
